import { Issue, TeamMember, Project, Cycle, IssueStatus, IssuePriority } from './types';

export const TEAM_MEMBERS: TeamMember[] = [
  {
    id: 'usr-1',
    name: 'Elena Rostova',
    handle: 'erostova',
    role: 'Staff Systems Architect',
    initials: 'ER',
    color: '#5E6AD2',
    capacityPts: 24,
  },
  {
    id: 'usr-2',
    name: 'Marcus Vance',
    handle: 'mvance',
    role: 'Principal Runtime Engineer',
    initials: 'MV',
    color: '#27C383',
    capacityPts: 21,
  },
  {
    id: 'usr-3',
    name: 'Sora Takahashi',
    handle: 'stakahashi',
    role: 'Design Systems Lead',
    initials: 'ST',
    color: '#E5A83B',
    capacityPts: 18,
  },
  {
    id: 'usr-4',
    name: 'Devon Kestrel',
    handle: 'dkestrel',
    role: 'Distributed Storage Eng',
    initials: 'DK',
    color: '#8B95E5',
    capacityPts: 20,
  },
  {
    id: 'usr-5',
    name: 'Aria Lin',
    handle: 'alin',
    role: 'Security & Cryptography',
    initials: 'AL',
    color: '#EB5757',
    capacityPts: 16,
  },
];

export const PROJECTS: Project[] = [
  {
    id: 'prj-sync',
    name: 'Local-First Sync Engine v3',
    key: 'SYNC',
    leadId: 'usr-1',
    status: 'On Track',
    targetDate: 'Oct 28',
    description: 'Zero-latency IndexedDB delta compression and WebSocket multiplexing for offline-first workspaces.',
    progress: 74,
  },
  {
    id: 'prj-grid',
    name: 'Virtualized Canvas & Grid',
    key: 'GRID',
    leadId: 'usr-3',
    status: 'On Track',
    targetDate: 'Nov 12',
    description: '120fps WebGL-acceleratedswimlane rendering and sub-millisecond keyboard navigation.',
    progress: 58,
  },
  {
    id: 'prj-auth',
    name: 'Zero-Trust Session Enclave',
    key: 'AUTH',
    leadId: 'usr-5',
    status: 'At Risk',
    targetDate: 'Nov 04',
    description: 'Hardware-backed WebAuthn passkey rotation and granular RBAC policy evaluation.',
    progress: 41,
  },
  {
    id: 'prj-cli',
    name: 'Slate CLI & Git Hooks',
    key: 'CLI',
    leadId: 'usr-2',
    status: 'Completed',
    targetDate: 'Oct 02',
    description: 'Automated branch naming, PR status synchronization, and terminal issue triage.',
    progress: 100,
  },
];

export const CYCLES: Cycle[] = [
  {
    id: 'cyc-42',
    number: 42,
    name: 'Cycle 42 — Core Delta & Sub-ms Navigation',
    startDate: 'Oct 01',
    endDate: 'Oct 14',
    status: 'Active',
    scopePoints: 68,
    completedPoints: 46,
    dailyBurnup: [
      { day: 'Oct 01', scope: 58, completed: 4, ideal: 5 },
      { day: 'Oct 03', scope: 60, completed: 12, ideal: 14 },
      { day: 'Oct 05', scope: 64, completed: 23, ideal: 24 },
      { day: 'Oct 07', scope: 68, completed: 35, ideal: 34 },
      { day: 'Oct 09', scope: 68, completed: 46, ideal: 44 },
      { day: 'Oct 11', scope: 68, completed: 46, ideal: 55 },
      { day: 'Oct 14', scope: 68, completed: 46, ideal: 68 },
    ],
  },
  {
    id: 'cyc-43',
    number: 43,
    name: 'Cycle 43 — Multi-Region Read Replicas',
    startDate: 'Oct 15',
    endDate: 'Oct 28',
    status: 'Upcoming',
    scopePoints: 54,
    completedPoints: 0,
    dailyBurnup: [],
  },
];

export const STATUS_CONFIG: Record<
  IssueStatus,
  { label: string; color: string; tint: string; order: number; shortcut: string }
> = {
  backlog: {
    label: 'Backlog',
    color: '#6E7681',
    tint: 'rgba(110, 118, 129, 0.12)',
    order: 0,
    shortcut: '1',
  },
  todo: {
    label: 'Todo',
    color: '#c6c5d5',
    tint: 'rgba(198, 197, 213, 0.12)',
    order: 1,
    shortcut: '2',
  },
  in_progress: {
    label: 'In Progress',
    color: '#E5A83B',
    tint: 'rgba(229, 168, 59, 0.12)',
    order: 2,
    shortcut: '3',
  },
  in_review: {
    label: 'In Review',
    color: '#8B95E5',
    tint: 'rgba(139, 149, 229, 0.14)',
    order: 3,
    shortcut: '4',
  },
  done: {
    label: 'Done',
    color: '#27C383',
    tint: 'rgba(39, 195, 131, 0.12)',
    order: 4,
    shortcut: '5',
  },
  blocked: {
    label: 'Blocked',
    color: '#EB5757',
    tint: 'rgba(235, 87, 87, 0.14)',
    order: 5,
    shortcut: '6',
  },
};

export const PRIORITY_CONFIG: Record<
  IssuePriority,
  { label: string; color: string; tint: string; bars: number; shortcut: string }
> = {
  urgent: {
    label: 'Urgent',
    color: '#EB5757',
    tint: 'rgba(235, 87, 87, 0.14)',
    bars: 4,
    shortcut: '1',
  },
  high: {
    label: 'High',
    color: '#E5A83B',
    tint: 'rgba(229, 168, 59, 0.12)',
    bars: 3,
    shortcut: '2',
  },
  medium: {
    label: 'Medium',
    color: '#8B95E5',
    tint: 'rgba(139, 149, 229, 0.12)',
    bars: 2,
    shortcut: '3',
  },
  low: {
    label: 'Low',
    color: '#6E7681',
    tint: 'rgba(110, 118, 129, 0.12)',
    bars: 1,
    shortcut: '4',
  },
  none: {
    label: 'No Priority',
    color: '#454652',
    tint: 'rgba(69, 70, 82, 0.12)',
    bars: 0,
    shortcut: '0',
  },
};

export const INITIAL_ISSUES: Issue[] = [
  {
    id: 'SLT-104',
    title: 'Implement CRDT vector clock compaction for offline sync queues',
    description:
      'When client workspaces remain offline for >72 hours, the local IndexedDB mutation log accumulates redundant state tombstones. We need a deterministic compaction pass before opening the WebSocket sync handshake so payload frames stay under 64KB.',
    status: 'in_progress',
    priority: 'urgent',
    assigneeId: 'usr-1',
    projectId: 'prj-sync',
    cycleId: 'cyc-42',
    estimate: 8,
    labels: ['Sync Engine', 'Storage'],
    dueDate: 'Oct 10',
    createdAt: 'Oct 01',
    updatedAt: '14m ago',
    prNumber: '#842',
    branchName: 'erostova/slt-104-crdt-compaction',
    subtasks: [
      { id: 'st-1', title: 'Benchmark tombstone sweep on 50k synthetic mutations', completed: true },
      { id: 'st-2', title: 'Serialize compacted lamport timestamps into binary header', completed: true },
      { id: 'st-3', title: 'Add property-based fuzz tests for concurrent merge', completed: false },
    ],
    activity: [
      {
        id: 'act-1',
        authorId: 'usr-1',
        type: 'commit',
        content: 'feat(sync): compact causal history trees before handshake (#842)',
        timestamp: '2h ago',
        meta: 'a94f12c',
      },
      {
        id: 'act-2',
        authorId: 'usr-4',
        type: 'comment',
        content: 'Verified memory ceiling drops from 48MB to 6.2MB on large workspaces.',
        timestamp: '45m ago',
      },
    ],
  },
  {
    id: 'SLT-108',
    title: 'Fix sub-pixel border jitter during horizontal swimlane momentum scroll',
    description:
      'On 2x Retina displays, 1px hairline borders inside virtualized swimlane columns flicker when horizontal scroll velocity exceeds 1200px/s. Force GPU layer promotion and snap column translates to integer device pixels.',
    status: 'in_progress',
    priority: 'high',
    assigneeId: 'usr-3',
    projectId: 'prj-grid',
    cycleId: 'cyc-42',
    estimate: 5,
    labels: ['UI Craft', 'Performance'],
    dueDate: 'Oct 11',
    createdAt: 'Oct 02',
    updatedAt: '38m ago',
    prNumber: '#849',
    branchName: 'stakahashi/slt-108-subpixel-snap',
    subtasks: [
      { id: 'st-4', title: 'Round transform matrix X offsets to devicePixelRatio', completed: true },
      { id: 'st-5', title: 'Audit composite layer memory in Chrome DevTools', completed: false },
    ],
    activity: [
      {
        id: 'act-3',
        authorId: 'usr-3',
        type: 'status_change',
        content: 'Moved issue from Todo to In Progress',
        timestamp: '1d ago',
      },
    ],
  },
  {
    id: 'SLT-112',
    title: 'Add directional J/K keyboard focus ring navigation across grouped rows',
    description:
      'Users navigating via J/K or ArrowUp/ArrowDown in List and Board views should experience zero-latency focus movement with automatic scrollIntoView buffering and a crisp 1px #5E6AD2 focus ring.',
    status: 'in_review',
    priority: 'high',
    assigneeId: 'usr-3',
    projectId: 'prj-grid',
    cycleId: 'cyc-42',
    estimate: 3,
    labels: ['Keyboard', 'Accessibility'],
    dueDate: 'Oct 09',
    createdAt: 'Oct 02',
    updatedAt: '1h ago',
    prNumber: '#851',
    branchName: 'stakahashi/slt-112-jk-navigation',
    subtasks: [
      { id: 'st-6', title: 'Bind J/K and 1-6 status hotkeys at window level', completed: true },
      { id: 'st-7', title: 'Prevent shortcut firing when input/textarea is focused', completed: true },
    ],
    activity: [
      {
        id: 'act-4',
        authorId: 'usr-2',
        type: 'comment',
        content: 'LGTM! Tested rapid key-repeat at 60Hz—zero dropped frames.',
        timestamp: '1h ago',
      },
    ],
  },
  {
    id: 'SLT-115',
    title: 'Blocked on upstream WebCrypto Ed25519 key wrapping spec in Safari 18',
    description:
      'Hardware enclave session binding throws NotSupportedError when exporting wrapped PKCS#8 keys in WebKit. Evaluating WASM fallback vs polyfill layer until upstream patch lands.',
    status: 'blocked',
    priority: 'urgent',
    assigneeId: 'usr-5',
    projectId: 'prj-auth',
    cycleId: 'cyc-42',
    estimate: 5,
    labels: ['Security', 'WebAuthn'],
    dueDate: 'Oct 08',
    createdAt: 'Oct 03',
    updatedAt: '3h ago',
    branchName: 'alin/slt-115-ed25519- enclave',
    subtasks: [
      { id: 'st-8', title: 'Isolate WebKit reproduction case', completed: true },
      { id: 'st-9', title: 'Implement constant-time WASM fallback wrapper', completed: false },
    ],
    activity: [
      {
        id: 'act-5',
        authorId: 'usr-5',
        type: 'status_change',
        content: 'Flagged as Blocked due to WebKit Bug #281904',
        timestamp: '3h ago',
      },
    ],
  },
  {
    id: 'SLT-119',
    title: 'Streamline Command+K palette fuzzy matcher with trigram indexing',
    description:
      'Upgrade the Command+K quick switcher to rank exact issue ID prefixes (e.g. SLT-119) ahead of body prose matches and highlight matched character tokens.',
    status: 'todo',
    priority: 'medium',
    assigneeId: 'usr-2',
    projectId: 'prj-grid',
    cycleId: 'cyc-42',
    estimate: 3,
    labels: ['Command Bar', 'Search'],
    dueDate: 'Oct 12',
    createdAt: 'Oct 03',
    updatedAt: '5h ago',
    subtasks: [
      { id: 'st-10', title: 'Weight issue key and title tokens 3x over description', completed: false },
      { id: 'st-11', title: 'Add instant status transition actions to palette', completed: false },
    ],
    activity: [],
  },
  {
    id: 'SLT-121',
    title: 'Zero-copy binary serialization for real-time cursor presence broadcasts',
    description:
      'Replace JSON stringification on ephemeral presence packets with fixed 24-byte ArrayBuffer structs to cut WebSocket bandwidth by 78%.',
    status: 'todo',
    priority: 'high',
    assigneeId: 'usr-4',
    projectId: 'prj-sync',
    cycleId: 'cyc-42',
    estimate: 5,
    labels: ['Sync Engine', 'Network'],
    dueDate: 'Oct 13',
    createdAt: 'Oct 04',
    updatedAt: '6h ago',
    subtasks: [],
    activity: [],
  },
  {
    id: 'SLT-124',
    title: 'Enforce strict tabular-nums across cycle velocity and burnup tooltips',
    description:
      'Audit all numeric counters, story point badges, and percentage cells to guarantee zero horizontal layout shift during live state updates.',
    status: 'done',
    priority: 'medium',
    assigneeId: 'usr-3',
    projectId: 'prj-grid',
    cycleId: 'cyc-42',
    estimate: 2,
    labels: ['UI Craft', 'Typography'],
    dueDate: 'Oct 06',
    createdAt: 'Oct 01',
    updatedAt: '2d ago',
    prNumber: '#831',
    branchName: 'stakahashi/slt-124-tabular-nums',
    subtasks: [
      { id: 'st-12', title: 'Apply font-variant-numeric: tabular-nums to all metric cells', completed: true },
    ],
    activity: [],
  },
  {
    id: 'SLT-127',
    title: 'Batch SQLite WAL checkpointing on background worker thread',
    description:
      'Offload write-ahead log fsync operations to a dedicated OPFS synchronous access handle inside a SharedWorker so main thread input latency never spikes above 2ms.',
    status: 'done',
    priority: 'urgent',
    assigneeId: 'usr-4',
    projectId: 'prj-sync',
    cycleId: 'cyc-42',
    estimate: 8,
    labels: ['Storage', 'Performance'],
    dueDate: 'Oct 05',
    createdAt: 'Oct 01',
    updatedAt: '3d ago',
    prNumber: '#828',
    branchName: 'dkestrel/slt-127-opfs-wal',
    subtasks: [
      { id: 'st-13', title: 'Configure OPFS SyncAccessHandle pool', completed: true },
      { id: 'st-14', title: 'Verify automatic recovery on tab crash', completed: true },
    ],
    activity: [],
  },
  {
    id: 'SLT-130',
    title: 'Implement Git webhook signature verification with HMAC-SHA256 rotation',
    description:
      'Support dual active webhook secrets during zero-downtime key rotation windows for enterprise GitHub Enterprise Server integrations.',
    status: 'done',
    priority: 'high',
    assigneeId: 'usr-5',
    projectId: 'prj-auth',
    cycleId: 'cyc-42',
    estimate: 5,
    labels: ['Security', 'CLI'],
    dueDate: 'Oct 06',
    createdAt: 'Oct 02',
    updatedAt: '2d ago',
    prNumber: '#835',
    subtasks: [],
    activity: [],
  },
  {
    id: 'SLT-133',
    title: 'Support multi-select Shift+Click range actions in high-density list view',
    description:
      'Allow engineers to select contiguous ranges of issues and apply bulk status, priority, or cycle reassignments in a single atomic operation.',
    status: 'in_review',
    priority: 'medium',
    assigneeId: 'usr-2',
    projectId: 'prj-grid',
    cycleId: 'cyc-42',
    estimate: 5,
    labels: ['UI Craft', 'Keyboard'],
    dueDate: 'Oct 10',
    createdAt: 'Oct 04',
    updatedAt: '4h ago',
    prNumber: '#853',
    subtasks: [],
    activity: [],
  },
  {
    id: 'SLT-136',
    title: 'Schema migration runner for optimistic client-side custom fields',
    description:
      'Design a deterministic forward-only schema migration graph when workspaces upgrade local cache schemas across major versions.',
    status: 'backlog',
    priority: 'medium',
    assigneeId: 'usr-1',
    projectId: 'prj-sync',
    cycleId: 'cyc-43',
    estimate: 5,
    labels: ['Sync Engine', 'Architecture'],
    createdAt: 'Oct 05',
    updatedAt: '1d ago',
    subtasks: [],
    activity: [],
  },
  {
    id: 'SLT-139',
    title: 'Automatic stale PR detection and cycle rollover warnings',
    description:
      'Surface a non-intrusive indicator when an issue remains in In Review for >48h without CI pipeline activity.',
    status: 'backlog',
    priority: 'low',
    assigneeId: 'usr-2',
    projectId: 'prj-cli',
    cycleId: 'cyc-43',
    estimate: 3,
    labels: ['CLI', 'Workflow'],
    createdAt: 'Oct 06',
    updatedAt: '1d ago',
    subtasks: [],
    activity: [],
  },
  {
    id: 'SLT-141',
    title: 'Memory leak in WebSocket reconnection exponential backoff timer',
    description:
      'Uncleaned abort controllers retain closure references to stale workspace buffers when switching networks rapidly on macOS.',
    status: 'todo',
    priority: 'urgent',
    assigneeId: 'usr-1',
    projectId: 'prj-sync',
    cycleId: 'cyc-42',
    estimate: 3,
    labels: ['Network', 'Bug'],
    dueDate: 'Oct 09',
    createdAt: 'Oct 07',
    updatedAt: '22m ago',
    subtasks: [
      { id: 'st-15', title: 'Dispose AbortController listeners on socket close', completed: false },
    ],
    activity: [],
  },
  {
    id: 'SLT-144',
    title: 'Audit WCAG AA contrast ratios on muted metadata tokens in dim rooms',
    description:
      'Verify #908f9e and #c6c5d5 text tokens maintain >=4.5:1 contrast against #121417 card surfaces.',
    status: 'done',
    priority: 'low',
    assigneeId: 'usr-3',
    projectId: 'prj-grid',
    cycleId: 'cyc-42',
    estimate: 2,
    labels: ['Accessibility', 'UI Craft'],
    dueDate: 'Oct 04',
    createdAt: 'Oct 01',
    updatedAt: '4d ago',
    prNumber: '#821',
    subtasks: [],
    activity: [],
  },
];
